version: '3.8'

services:
  backend:
    image: ${DOCKER_USER}/clinica-dental-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-east-1
      - AWS_COGNITO_REGION=us-east-1
      - AWS_COGNITO_USER_POOL_ID=us-east-1_h8YmMJNGE
      - AWS_COGNITO_CLIENT_ID=35rmo40a90o45qpc05sap29cmv
      - AWS_S3_BUCKET=clinicadental-media-183295432907-us-east-1-an
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - ORACLE_USERNAME=ADMIN
      - CONNECTION_ALIAS=x8fvkl9ob734pm0e_tp
      - WALLET_PATH=/app/wallet
      - API_PORT=8080

  frontend:
    image: ${DOCKER_USER}/clinica-dental-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
